### ISSUE TITLE
Not working in Unix based environments

### ISSUE THREAD

**Issue by MathieuDerelle** [BluuArc/BFFrameAnimator#2]
See the backtrace below, the folder separator does not take into account the environment 

Choose the parent directory for all units.
Choose list.txt that contains a list of IDs to process.
Couldn't save media path to a file
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getSpecificFiles: No files found
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getSpecificFiles: No files found
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getFilesInPath: Directory [/Users/mathieu/Downloads/example/Units\50265] is empty or not found.
Error in FileManagement.getSpecificFiles: No files found
Error in BFFrameMaker.processUnit: missing files for 50265
NullPointerException encountered in animation process

**Comment by BluuArc** [comment]
Can you confirm that your issue has been addressed with the v2.1.1 release?

**Comment by MathieuDerelle** [comment]
it works !

Thanks, I won't have to launch an expensive VM each time now.

NB: there is another bug with the windows where your choose directories/.txt  
They randomly don't want to appear, so nothing happen, you get stuck at one of the 3 lines 
- Choose the destination directory for all GIFs.
- Choose the parent directory for all units.
- Choose list.txt that contains a list of IDs to process.

But it's minor, you just have to restart and restart untill it's ok

**Comment by BluuArc** [comment]
It's a possibility that the FileChooser windows are hidden behind another window (e.g. a Terminal window). You can try using something like ALT+TAB to find the hidden window.

**Comment by matxx** [comment]
btw, it was not hidden behing other windows and some other day it was really atrocious cause event restart after restart, it was not working all.
But I've found that you can put them in the line command, so usefull

**Comment by MathieuDerelle** [comment]
oh sorry, I was logged on another account :D
